### ISSUE TITLE
Вариант перевода для /guide/displaying-data

### ISSUE THREAD

**Issue by trubachoff** [obenjiro/angular-ru-docs#128]
URL: https://angular24.ru/guide/displaying-data
--------------------------
Текущий перевод:
 The backtick (`) -Какое это не тот же самый характера, как один цитата (') - позволяет вам составить строку из нескольких строк, что делает HTML более читабелен.
--------------------------
Предлагаю:
Обратная кавычка (`) -- это не смвол однарной кавычки ('), позволяет вам размещать шаблон на нескольких строках, что делает HTML более читабельным.

**Comment by obenjiro** [comment]
Спасибо :) На дня выложу сборку с переводом
