### ISSUE TITLE
Вариант перевода для /guide/aot-compiler#%D0%BA%D0%BE%D0%B4-%D1%81%D0%B2%D0%BE%D1%80%D0%B0%D1%87%D0%B8%D0%B2%D0%B0%D0%B5%D1%82%D1%81%D1%8F

### ISSUE THREAD

**Issue by houston-vlad** [obenjiro/angular-ru-docs#21]
URL: https://angular24.ru/guide/aot-compiler#%D0%BA%D0%BE%D0%B4-%D1%81%D0%B2%D0%BE%D1%80%D0%B0%D1%87%D0%B8%D0%B2%D0%B0%D0%B5%D1%82%D1%81%D1%8F
--------------------------
Текущий перевод:
константа 
--------------------------
Предлагаю:
константу

**Comment by obenjiro** [comment]
Спасибо огромное :) на днях выложу сборку с переводом
