### ISSUE TITLE
Вариант перевода для /docs

### ISSUE THREAD

**Issue by astrohome** [obenjiro/angular-ru-docs#24]
URL: https://angular24.ru/docs
--------------------------
Текущий перевод:
Вы можете сидеть с нами!
--------------------------
Предлагаю:
Мы рады каждому!

**Comment by astrohome** [comment]
Это отсылка к фильму и к известной анти-буллинговой акции "You can sit with us!", дословно - "Можешь сидеть с нами!" при ситуации в столовой, когда кто-то не может поесть за одним столом с другими учениками, потому что его/ее считают аутсайдером

**Comment by obenjiro** [comment]
Спасибо огромное :) на днях выложу сборку с переводом

Отдельное спасибо за объяснение ремарки. Никогда бы не подумал, даже учитывая то что слышал в разных сериалах эту фразу
