### ISSUE TITLE
Вариант перевода для /guide/dependency-injection-providers

### ISSUE THREAD

**Issue by Krasnov8953** [obenjiro/angular-ru-docs#33]
URL: https://angular24.ru/guide/dependency-injection-providers
--------------------------
Текущий перевод:
Зависимость поставщикнастраивает инжектор с знаком DI
--------------------------
Предлагаю:
Провайдер зависимости настраивает инжектор с помощью DI токена

**Comment by obenjiro** [comment]
Спасибо огромное :) на днях выложу сборку с переводом
