### ISSUE TITLE
Вариант перевода для /guide/dependency-injection-providers

### ISSUE THREAD

**Issue by Krasnov8953** [obenjiro/angular-ru-docs#34]
URL: https://angular24.ru/guide/dependency-injection-providers
--------------------------
Текущий перевод:
Этот регистратор получает пользователя от введенного UserService.
--------------------------
Предлагаю:
Этот логгер получает пользователя от внедренного UserService.

**Comment by obenjiro** [comment]
Спасибо огромное :) на днях выложу сборку с переводом
