### ISSUE TITLE
Вариант перевода для /start

### ISSUE THREAD

**Issue by houston-vlad** [obenjiro/angular-ru-docs#37]
URL: https://angular24.ru/start
--------------------------
Текущий перевод:
что вы ожидать, сохранить, а затем нажмите кнопку обновления.
--------------------------
Предлагаю:
что вы ожидаете, сохраните, а затем нажмите кнопку обновления.

**Comment by obenjiro** [comment]
Спасибо :) Соединил с другим pr и уже выкатил
