### ISSUE TITLE
Вариант перевода для /guide/architecture-services

### ISSUE THREAD

**Issue by seriogatatarinov** [obenjiro/angular-ru-docs#38]
URL: https://angular24.ru/guide/architecture-services
--------------------------
Текущий перевод:
Услуги могут зависеть от других услуг. Например, вот HeroService который зависит от Logger услуг, а также использование BackendService для получения героев. Эта услуга в свою очередь может зависеть от HttpClient для асинхронной выборки героев с сервера.
--------------------------
Предлагаю:
Сервисы могут зависеть от других сервисов. Например, вот HeroService который зависит от Logger сервиса, а также использует BackendService для получения героев. Этот сервис в свою очередь может зависеть от HttpClient для асинхронной выборки героев с сервера.

**Comment by obenjiro** [comment]
Спасибо огромное :) на днях выложу сборку с переводом
