### ISSUE TITLE
Вариант перевода для /start/start-data

### ISSUE THREAD

**Issue by tyllo** [obenjiro/angular-ru-docs#43]
URL: https://angular24.ru/start/start-data
--------------------------
Текущий перевод:
Обновите шаблон компонента доставки, чтобы отобразить типы доставки и цены, используя async **труба**:
--------------------------
Предлагаю:
Обновите шаблон компонента доставки, чтобы отобразить типы доставки и цены, используя async **pipe**:

**Comment by obenjiro** [comment]
В ближайшее время будем решать что делать c англицизмами и стоит ли переводить термины  https://github.com/obenjiro/angular-ru-docs/issues/80 

Остальную часть перевода уже поменяли и подмерджили. Спасибо :)
