### ISSUE TITLE
Вариант перевода для /guide/dependency-injection-providers

### ISSUE THREAD

**Issue by RenJeka** [obenjiro/angular-ru-docs#50]
URL: https://angular24.ru/guide/dependency-injection-providers
--------------------------
Текущий перевод:
В следующем фрагменте кода показано, как класс, заданный как providers Значение раскрывается в полный объект провайдера.
--------------------------
Предлагаю:
В следующем фрагменте кода показано, как класс, заданный в качестве значения для providers, раскрывается в полный объект провайдера.

**Comment by obenjiro** [comment]
Спасибо огромное :) на днях выложу сборку с переводом
