### ISSUE TITLE
Вариант перевода для /guide/dependency-injection#token

### ISSUE THREAD

**Issue by RenJeka** [obenjiro/angular-ru-docs#51]
URL: https://angular24.ru/guide/dependency-injection#token
--------------------------
Текущий перевод:
Инжектор поддерживает внутреннюю токена-провайдера, на карту которую он ссылается, когда попросил зависимость.
--------------------------
Предлагаю:
Инжектор поддерживает внутреннюю карту токена-провайдера, на которую он ссылается при запросе зависимости.

**Comment by obenjiro** [comment]
Спасибо огромное :) на днях выложу сборку с переводом
