### ISSUE TITLE
Вариант перевода для /guide/dependency-injection-providers

### ISSUE THREAD

**Issue by RenJeka** [obenjiro/angular-ru-docs#52]
URL: https://angular24.ru/guide/dependency-injection-providers
--------------------------
Текущий перевод:
В таких случаях вы можете использоватьзаводской провайдер. Поставщики фабрики также могут быть полезны при создании экземпляра зависимости от сторонняя библиотека, не предназначенная для работы с DI.
--------------------------
Предлагаю:
В таких случаях вы можете использовать фабрику провайдеров (factory provider).Поставщики фабрики также могут быть полезны при создании экземпляра зависимости из сторонней библиотеки, которая не предназначена для работы с DI.

**Comment by obenjiro** [comment]
Спасибо огромное :) на днях выложу сборку с переводом
