### ISSUE TITLE
Вариант перевода для /guide/glossary#workspace

### ISSUE THREAD

**Issue by irustm** [obenjiro/angular-ru-docs#7]
**URL**: https://angular24.ru/guide/glossary#workspace

**Текущий перевод:**
Узнайте больше о зонах в этом Брайан Форд видео.

**Предлагаю**:
Узнайте больше о зонах в этом видео от Brian Ford

**Comment by obenjiro** [comment]
Спасибо огромное :) на днях выложу сборку с переводом
