### ISSUE TITLE
Вариант перевода для /guide/dependency-injection

### ISSUE THREAD

**Issue by meowhunter** [obenjiro/angular-ru-docs#77]
URL: https://angular24.ru/guide/dependency-injection
--------------------------
Текущий перевод:
В этом руководстве объясняется, как DI работает в Angular, и как вы используете его, чтобы сделать ваши приложения гибкими, эффективными и надежными, а также тестируемыми и обслуживаемыми.
--------------------------
Предлагаю:
В этом руководстве объясняется, как DI работает в Angular, и как использовать его, чтобы сделать ваши приложения гибкими, эффективными и надежными, а также тестируемыми и обслуживаемыми.

**Comment by obenjiro** [comment]
Спасибо :) на днях выложу сборку с переводом
