### ISSUE TITLE
Вариант перевода для /analytics

### ISSUE THREAD

**Issue by iamvasiliev143** [obenjiro/angular-ru-docs#8]
URL: https://angular24.ru/analytics
--------------------------
Текущий перевод:
 
# Usage Metrics Gathering
You can help the Angular Team to prioritize features and improvements by permitting the Angular
team to send command-line command usage statistics to Google. The Angular Team does not collect usage statistics unless you explicitly opt in during the Angular CLI installation or upgrade.

## What is collected?
Usage analytics include the commands and selected flags for each execution. Usage analytics may
include the following information:

- Your operating system (Mac, Linux distribution, Windows) and its version.
- Number of CPUs, amount of RAM.
- Node and Angular CLI version (local version only).
- How long each command took to initialize and execute.
- Command name that was run.
- For Schematics commands (add, generate, new and update), a list of whitelisted flags.
- For build commands (build, serve), the number and size of bundles (initial and lazy),
  compilation units, the time it took to build and rebuild, and basic Angular-specific
  API usage.
- Error code of exceptions and crash data. No stack trace is collected.

Only Angular owned and developed schematics and builders are reported. Third-party schematics and
builders do not send data to the Angular Team.

## Opting in
When installing the Angular CLI or upgrading an existing version, you are prompted to allow global
collection of usage statistics. If you say no or skip the prompt, no data is collected.

Starting with version 8, we added the `analytics` command to the CLI. You can change your opt-in
decision at any time using this command.

### Disabling usage analytics
To disable analytics gathering, run the following command:

```bash
# Disable all usage analytics.
ng analytics off
```

### Enabling usage analytics
To enable usage analytics, run the following command:

```bash
# Enable all usage analytics.
ng analytics on
```

### Prompting
To prompt the user again about usage analytics, run the following command:

```bash
# Prompt for all usage analytics.
ng analytics prompt
```

--------------------------
Предлагаю:
# Сбор метрик использования
Вы можете помочь команде Angular Team расставить приоритеты по функциям и улучшениям, позволив команде Angular Team отправить статистику использования команд из командной строки в Google. Команда Angular Team не собирает статистику использования, если только вы явно не согласились на нее во время установки или обновления Angular CLI.

## Что собрано?
Аналитика использования включает в себя команды и выбранные флаги для каждого выполнения. Аналитика использования может включать следующую информацию:

- Ваша операционная система (Mac, дистрибутив Linux, Windows) и ее версия.
- Количество процессоров, объем оперативной памяти.
- Node и Angular версия CLI (только локальная версия).
- Сколько времени заняла инициализация и выполнение каждой команды.
- Имя команды, которая была выполнена.
- Для команд Schematics (добавить, сгенерировать, обновить и обновить), список флагов белого списка.
- Для команд сборки (build, serve), количество и размер пакетов (начальных и ленивых), 
 компиляционные единицы, время, затраченное на сборку и перестройку, и базовые Angular специфики использования API.
- Ошибочный код исключений и данных об авариях. Не собрана трасса стека.

Сообщаются только Angular принадлежащие и разработанные схемы и строители. Схемы сторонних разработчиков и строители не посылают данные в команду Angular Team.

## Соглашение
При установке Angular CLI или обновлении существующей версии, вам будет предложено разрешить глобальный сбор статистики использования. Если вы скажете "нет" или пропустите подсказку, данные не будут собраны.

Начиная с версии 8, мы добавили в CLI команду `analytics`. Вы можете изменить вашу опцию
разрешения в любое время с помощью этой команды.

### Отключение анализа использования
Чтобы отключить сбор аналитических данных, выполните следующую команду:

```bash
# Отключить аналитику использования.
ng analytics off
```

### Разрешить аналитику использования
Чтобы включить анализ использования, выполните следующую команду:

```bash
# Включить аналитику всего использования.
ng analytics on
```

### Prompting
Чтобы снова запросить пользователя об анализе использования, выполните следующую команду:

```bash
# Запрос на использование аналитики.
ng analytics prompt
```

**Comment by obenjiro** [comment]
Спасибо огромное :) на днях выложу сборку с переводом
