### ISSUE TITLE
Вариант перевода для /api/forms/AbstractControl#description

### ISSUE THREAD

**Issue by RenJeka** [obenjiro/angular-ru-docs#87]
URL: https://angular24.ru/api/forms/AbstractControl#description
--------------------------
Текущий перевод:
Он также определяет свойства которые являются общимивсех подклассов, как value значение, valid действительным, и dirty грязного. Так не должно быть Создан непосредственно.
--------------------------
Предлагаю:
Он также определяет свойства, которые являются общими для всех подклассов, такие как value, valid и dirty. Этот класс не должен реализовываться напрямую.

**Comment by obenjiro** [comment]
Спасибо :) на днях выложу сборку с переводом
