### ISSUE TITLE
Вариант перевода для /guide/http#testing-http-requests

### ISSUE THREAD

**Issue by chuguev** [obenjiro/angular-ru-docs#89]
URL: https://angular24.ru/guide/http#testing-http-requests
--------------------------
Текущий перевод:
чтобы вы могли afterEach() шаг:
--------------------------
Предлагаю:
чтобы вы могли поместить его в afterEach():

**Comment by obenjiro** [comment]
Спасибо :) на днях выложу сборку с переводом
