### ISSUE TITLE
Вариант перевода для /

### ISSUE THREAD

**Issue by nzhorn** [obenjiro/angular-ru-docs#9]
URL: https://angular24.ru/
--------------------------
Текущий перевод:
Изучите один способ создания приложений с Angular и повторно используйте свой код и возможности для создания приложений для любой цели развертывания. Для Интернета, мобильного Интернета, родного мобильного телефона и собственного рабочего стола.
--------------------------
Предлагаю:
Научитесь одному из способов построения приложения с Angular и получите возможность повторно использовать свой код и создавать приложения для разных платформ. Будь то веб, мобильные приложения, нативные мобильные приложения или нативный десктоп.

**Comment by obenjiro** [comment]
Спасибо огромное :) на днях выложу сборку с переводом
