### ISSUE TITLE
Вариант перевода для /features

### ISSUE THREAD

**Issue by RCnowak** [obenjiro/angular-ru-docs#95]
URL: https://angular24.ru/features
--------------------------
Текущий перевод:
создания приложений, похожих на приложения
--------------------------
Предлагаю:
создания приложений, похожих на нативные
--------------------------
Коммент:
В оригинале такого нет, но подразумевается

**Comment by obenjiro** [comment]
Спасибо :) на днях выложу сборку с переводом
